### PR TITLE
Adding Emergency page

### PR DESCRIPTION
**Pull request by 21vidushi**
Desktop View
Screenshot (45)

Mobile View
Screenshot (49)

### CODE REVIEW

**Review by Ash-2k3 — CHANGES_REQUESTED** [review]
@21vidushi Can you please move the images to the [assets](https://github.com/AMBU-The-Unified-HealthCare-System/Ambu-Web-App/tree/main/app/assets) folder ? Within this folder, make a new folder which should be named after the web page you are creating and then place all the images there.

**Comment by Ash-2k3** [comment]
Thanks @21vidushi, took a quick pass and left some comments, PTAL.

Also: I think web view looks good but I am not sure if that's the case for mobile view, the fonts seem to be quite big also some of the sections seems to be overlapping.

@Yash080902  Can you also take a look at the ss attached in PR description and suggest any changes if needed ?

**Comment by Yash080902** [comment]
Yeah!
@Ash-2k3 , I also agree with your statement that this website is not responsive. Vidushi has mentioned Akshat's performance on responsiveness several times, so I have decided to explain the concept of responsiveness to him in a one-on-one session.

**Comment by 21vidushi** [comment]
@Ash-2k3 okay, I will move the images in asset folder.

**Pull request closed without merging**
